### ISSUE TITLE
gpu support on new server

### ISSUE THREAD

**Issue by Highlife1911** [HPI-DeepLearning/SegMed#11]
man kann zur zeit keine gpu tasks in der segmed environment ausführen

**Comment by WGierke** [comment]
virtualenv "segmed_gpu" now detects both GPUs
![screenshot from 2017-06-22 13-06-34](https://user-images.githubusercontent.com/6676439/27431138-b1bf9e46-574b-11e7-993b-9b428a0a5e6c.png)

**Comment by Highlife1911** [comment]
This might be true but this environment lacks support to other common modules like scipy.

**Comment by WGierke** [comment]
Sorry about that. I installed the missing dependencies. If you miss some requirements at some later point, just install them in the virtual environment using `pip install x`.
