### ISSUE TITLE
correct handling of multiple gpus

### ISSUE THREAD

**Issue by Highlife1911** [HPI-DeepLearning/SegMed#12]
when using a server with multiple gpus, only allow one gpu to be used to be consistent with labshare. just wrapping everything in `with tf.device('/gpu:0'):` fails because some instructions are not allowed in with mode.

**Comment by WGierke** [comment]
[SO](https://stackoverflow.com/questions/36668467/change-default-gpu-in-tensorflow) says it's possible to specify the used gpu via the CUDA_VISIBLE_DEVICES environment variable. 
`CUDA_VISIBLE_DEVICES=1 python my_script.py` would make tensorflow in my_script.py to only see gpu1.
I guess that this variable has to be set before tensorflow is loaded. Thus, it'd be difficult to implement this "GPU switch" in Python code. 
My proposal: let's always execute `CUDA_VISIBLE_DEVICES=0,1` before running the model script. We would then be easily able to adapt the variable assignment to the specific GPUs we need.
