### ISSUE TITLE
implement test modes

### ISSUE THREAD

**Issue by Highlife1911** [HPI-DeepLearning/SegMed#23]
- [x] implement contest mode
- [x] do not apply image augmentation in test or contest mode
- [x] scale image back to original size in contest mode
- [x] do not output batches. Output single images instead.
- [x] keep filename in contest mode

**Comment by WGierke** [comment]
to evaluate the trained model with respect to the metrics as specified in #18 or to output a random input image concatenated with its current prediction (like the test method was implemented in pix2pix)?

**Comment by Highlife1911** [comment]
we should have 3 modes: train, test and contest. contest is still missing and should produce output images without the input images

**Comment by WGierke** [comment]
should the output image be concatenated with the input ground truth? or should there be no ground trust such that we can use the contest mode for the prediction of an uploaded image to our web server?

**Comment by Highlife1911** [comment]
to keep the existing interface the ground truth must be present in the input, but the generator does not use it so it can be anything.
