### ISSUE TITLE
Train survival rate

### ISSUE THREAD

**Issue by Chaoste** [HPI-DeepLearning/SegMed#29]
Train on the brain images and the age via a fusion layer (concatenate or fully connect).

Images Input: 32 * 7 * WIDTH * HEIGHT
- 32 slices of one person in one direction
- 7 Images dimensions (3 are the tumor returned by the other model, 4 are the different modalities of the brain)

- CNN for analyzing the images (Conv3D?)
- Haojin suggested using WordVec (by Google) for analyzing the age -> Just use One-Hot Encoding; amount of bins --> one for each year/decade? Analyze the input data by comparing the survival rate for people of almost the same age.

**Comment by WGierke** [comment]
For clarification
![img_20170703_164041](https://user-images.githubusercontent.com/6676439/27797588-8730fa0a-600e-11e7-9f32-3d41ffac7578.jpg)
